version: "3.8"
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: hilchfrei
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DATABASE_URL: mysql://root:root_password@db:3306/hilchfrei
    volumes:
      - .:/app

volumes:
  db:
