version: "3.8"
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: hilchfrei
    ports:
      - "3306:3306"
    healthcheck:
      test: "mysql -uroot -p root_password content -e 'select 1'"
      interval: 1s
      retries: 120
    volumes:
      - db:/var/lib/mysql

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://root:root_password@db:3306/hilchfrei
    restart: always
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  db:
